version: '3.8'
services:
  chatpostgre:
    container_name: chat_postgre
    image: postgres
    restart: "no"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chatappdb
    ports:
      - "5432:5432"

  rabbitmq3:
    container_name: chat_rabbit_mq
    image: rabbitmq:3.8-management-alpine
    restart: "no"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    container_name: chat_redis
    restart: "no"
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"